# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39b2471dcf74cae86f8b6c294000fc3b000d4270cd62778ad7070a51e0d56fe1373caba3cc25c4f752942a50edd2c509f4619d9d05009206f450e6bc216df5d7

test:
  secret_key_base: cbd277afb982fb3a306cbcc040c88478ab486bda3381812216921f548317fde52b2fbf487648c2e275c4073f501450b4f774bfd9c44940b79d4409dfb8ab0fb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
